### ISSUE TITLE
US #2 Modify Database for Bookmark Feature

### ISSUE THREAD

**Issue by wandrew004** [CMU-313/nodebb-f24-team-penguins#10]
## Description

Create a new bookmarks table in the database. Can also extend bookmark into existing table but likely easier and better to decouple from existing database tables.

## Dependencies

- Specification document for implementation. 

## Acceptance Criteria

Database table is created and manually tested. 

## Effort Estimate 

**16 hours**

**Comment by zhanwen22** [comment]
This was semi-completed with the openAPI, but we ran into many technical errors when attempting to do as such. Mainly with the routes and API having a bad schema.
