### ISSUE TITLE
US #2 Add logic for GET request

### ISSUE THREAD

**Issue by wandrew004** [CMU-313/nodebb-f24-team-penguins#14]
## Description

Add logic for GET request to the backend API. Also create corresponding unit tests.

## Dependencies

- Specification document for implementation. 
- Bookmark API routes are created and API documentation exists.

## Acceptance Criteria

API logic is created and unit tests are passing.

## Effort Estimate 

**12 hours**

**Comment by zhanwen22** [comment]
I added some put and delete logic in the bookmark.yaml, but it did not fully address this, since it was more about how we got it. I feel that we did not fully implement this, since much of the core is not accurately doing this.
