### ISSUE TITLE
US #2 Update Frontend for Bookmark Icon

### ISSUE THREAD

**Issue by wandrew004** [CMU-313/nodebb-f24-team-penguins#15]
## Description

Update frontend so that each post has a bookmark icon that can be toggled. 

## Dependencies

- Specification document for implementation. 

## Acceptance Criteria

Frontend is updated and manually tested

## Effort Estimate 

**4 hours**

**Comment by JordanFnsg** [comment]
Unfortunately, I was not able to work on this as we ended up focusing on user story 1.
