### ISSUE TITLE
US #2 Create Testing for UI

### ISSUE THREAD

**Issue by wandrew004** [CMU-313/nodebb-f24-team-penguins#17]
## Description

Create unit tests and manually test the UI to ensure that it's working properly

## Dependencies

- Specification document for implementation
- Bookmark API is working
- Frontend is updated

## Acceptance Criteria

Unit tests are passing and manual tests work.

## Effort Estimate 

**8 hours**

**Comment by JordanFnsg** [comment]
Unfortunately, I was not able to work on this as we ended up focusing on user story 1.
