### ISSUE TITLE
US #1 Testing for UI on Search Feature

### ISSUE THREAD

**Issue by wandrew004** [CMU-313/nodebb-f24-team-penguins#5]
## Description

Test UI for the updated search bar, search button, and rendered results. This includes unit tests and manual testing

## Dependencies

- Specification document for implementation. 
- Search API is working (likely with dummy results). 
- UI is completed: search bar, search button, rendering results.

## Acceptance Criteria

Unit Tests are passing and updates are seen in manual testing. 

## Effort Estimate 

**8 hours**

**Comment by JordanFnsg** [comment]
Ended up being unrelated to the changes that I had to make.
